# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-26 01:30
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mycyclediary_dot_com', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='bike',
            fields=[
                ('gear_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='mycyclediary_dot_com.gear')),
            ],
            bases=('mycyclediary_dot_com.gear',),
        ),
        migrations.CreateModel(
            name='shoe',
            fields=[
                ('gear_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='mycyclediary_dot_com.gear')),
            ],
            bases=('mycyclediary_dot_com.gear',),
        ),
    ]
