# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-26 01:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mycyclediary_dot_com', '0002_bike_shoe'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gear',
            name='primary',
            field=models.BooleanField(default=False),
        ),
    ]
