# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-26 01:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mycyclediary_dot_com', '0003_auto_20160225_1947'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gear',
            name='description',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
