# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-26 01:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mycyclediary_dot_com', '0004_auto_20160225_1948'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gear',
            name='brand_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='gear',
            name='model_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='gear',
            name='resource_state',
            field=models.PositiveSmallIntegerField(null=True),
        ),
    ]
