# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2017-05-15 04:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mycyclediary_dot_com', '0006_strava_webhook_subscription'),
    ]

    operations = [
        migrations.AddField(
            model_name='athlete',
            name='last_api_callback',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='strava_webhook_subscription',
            name='aspect_type',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='strava_webhook_subscription',
            name='created_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='strava_webhook_subscription',
            name='object_type',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='strava_webhook_subscription',
            name='strava_id',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='strava_webhook_subscription',
            name='updated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
