# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2017-05-15 04:10
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('mycyclediary_dot_com', '0007_auto_20170514_2301'),
    ]

    operations = [
        migrations.AddField(
            model_name='strava_webhook_subscription',
            name='verify_token',
            field=models.CharField(default=datetime.datetime(2017, 5, 15, 4, 10, 51, 772364, tzinfo=utc), max_length=32),
            preserve_default=False,
        ),
    ]
