# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2017-08-04 00:18
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mycyclediary_dot_com', '0008_strava_webhook_subscription_verify_token'),
    ]

    operations = [
        migrations.CreateModel(
            name='activity_bike',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity_id', models.BigIntegerField()),
                ('athlete', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('bike', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='mycyclediary_dot_com.bike')),
            ],
        ),
        migrations.CreateModel(
            name='activity_component',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity_id', models.BigIntegerField()),
                ('athlete', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='bike_component',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField()),
                ('athlete', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('bike', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='mycyclediary_dot_com.bike')),
            ],
        ),
        migrations.CreateModel(
            name='component',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.CharField(blank=True, max_length=255, null=True)),
                ('brand_name', models.CharField(blank=True, max_length=255, null=True)),
                ('model_name', models.CharField(blank=True, max_length=255, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('aquisition_date', models.DateTimeField(blank=True, null=True)),
                ('aquisition_distance_meters', models.FloatField()),
                ('retire_date', models.DateTimeField(blank=True, null=True)),
                ('battery_charged', models.DateTimeField(blank=True, null=True)),
                ('battery_replaced', models.DateTimeField(blank=True, null=True)),
                ('athlete', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RemoveField(
            model_name='strava_webhook_subscription',
            name='athlete',
        ),
        migrations.DeleteModel(
            name='strava_webhook_subscription',
        ),
        migrations.AddField(
            model_name='bike_component',
            name='component',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mycyclediary_dot_com.component'),
        ),
        migrations.AddField(
            model_name='bike_component',
            name='parent_component',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='parent_component_set', to='mycyclediary_dot_com.component'),
        ),
        migrations.AddField(
            model_name='activity_component',
            name='component',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='mycyclediary_dot_com.component'),
        ),
    ]
