# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2017-08-09 22:11
# Customized to cleanly handle the conversion of the base "gear" model to
# become child models of the "component" model
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion

def gear_fwd_func(apps, schema_editor):
    gear = apps.get_model('mycyclediary_dot_com', 'gear')
    db_alias = schema_editor.connection.alias
    gear_list = gear.objects.using(db_alias).all()
    # We're just going to nuke all of the gear, since the next scheduled
    # athlete sync will re-fetch all of the gear and enter it correctly into
    # the data model.
    for legacy_gear in gear_list:
        legacy_gear.delete()

def athlete_fwd_func(apps, schema_editor):
    athlete = apps.get_model('mycyclediary_dot_com', 'athlete')
    db_alias = schema_editor.connection.alias
    athlete_list = athlete.objects.using(db_alias).all()
    for curr_athlete in athlete_list:
        curr_athlete.username = curr_athlete.email
        curr_athlete.save()

class Migration(migrations.Migration):

    dependencies = [
        ('mycyclediary_dot_com', '0009_auto_20170803_1918'),
    ]

    operations = [
        migrations.CreateModel(
            name='component_component',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='activity_bike',
            name='athlete',
        ),
        migrations.RemoveField(
            model_name='activity_bike',
            name='bike',
        ),
        migrations.DeleteModel(
            name='bike_component',
        ),
        migrations.RemoveField(
            model_name='component',
            name='battery_charged',
        ),
        migrations.RemoveField(
            model_name='component',
            name='battery_replaced',
        ),
        migrations.AddField(
            model_name='component',
            name='battery_type',
            field=models.PositiveSmallIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='activity_component',
            name='activity_id',
            field=models.BigIntegerField(db_index=True),
        ),
        migrations.AlterField(
            model_name='athlete',
            name='strava_id',
            field=models.PositiveIntegerField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='gear',
            name='strava_id',
            field=models.CharField(blank=True, db_index=True, max_length=16, null=True),
        ),
        migrations.DeleteModel(
            name='activity_bike',
        ),
        migrations.AddField(
            model_name='component_component',
            name='athlete',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='component_component',
            name='component',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='child_component_set', to='mycyclediary_dot_com.component'),
        ),
        migrations.AddField(
            model_name='component_component',
            name='parent_component',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='parent_component_set', to='mycyclediary_dot_com.component'),
        ),
        migrations.AddField(
            model_name='gear',
            name='component_ptr',
            field=models.OneToOneField(auto_created=True, default=None, blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, to='mycyclediary_dot_com.component'),
            preserve_default=False,
        ),
        migrations.RunPython(gear_fwd_func),
        migrations.AlterField(
            model_name='gear',
            name='component_ptr',
            field=models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='mycyclediary_dot_com.component'),
            preserve_default=False,
        ),
        migrations.RemoveField(
            model_name='gear',
            name='athlete',
        ),
        migrations.RemoveField(
            model_name='gear',
            name='brand_name',
        ),
        migrations.RemoveField(
            model_name='gear',
            name='description',
        ),
        migrations.RemoveField(
            model_name='gear',
            name='model_name',
        ),
        migrations.RemoveField(
            model_name='gear',
            name='name',
        ),
        migrations.RunPython(athlete_fwd_func),
    ]
