# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2017-09-22 00:48
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mycyclediary_dot_com', '0010_auto_20170809_1711'),
    ]

    operations = [
        migrations.AlterField(
            model_name='component_component',
            name='component',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parent_component_set', to='mycyclediary_dot_com.component'),
        ),
        migrations.AlterField(
            model_name='component_component',
            name='parent_component',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='child_component_set', to='mycyclediary_dot_com.component'),
        ),
    ]
