# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-01-09 00:02
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mycyclediary_dot_com', '0012_auto_20180106_0249'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='athlete',
            managers=[
            ],
        ),
    ]
