# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-02-03 00:55
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mycyclediary_dot_com', '0013_auto_20180109_0002'),
    ]

    operations = [
        migrations.CreateModel(
            name='gear_component_profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('add_components', models.ManyToManyField(related_name='profile_add_components', to='mycyclediary_dot_com.component')),
                ('gear', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mycyclediary_dot_com.gear')),
                ('remove_components', models.ManyToManyField(related_name='profile_remove_components', to='mycyclediary_dot_com.component')),
            ],
        ),
    ]
