# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-02-09 19:08
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mycyclediary_dot_com', '0015_auto_20180205_2035'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='gear_component_profile',
            new_name='GearComponentProfile',
        ),
        migrations.AlterField(
            model_name='activity_component',
            name='athlete',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='activity_component',
            name='component',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='mycyclediary_dot_com.Component'),
        ),
        migrations.AlterField(
            model_name='bike',
            name='gear_ptr',
            field=models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='mycyclediary_dot_com.Gear'),
        ),
        migrations.AlterField(
            model_name='component',
            name='athlete',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='component_component',
            name='athlete',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='component_component',
            name='component',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parent_component_set', to='mycyclediary_dot_com.Component'),
        ),
        migrations.AlterField(
            model_name='component_component',
            name='parent_component',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='child_component_set', to='mycyclediary_dot_com.Component'),
        ),
        migrations.AlterField(
            model_name='gear',
            name='component_ptr',
            field=models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='mycyclediary_dot_com.Component'),
        ),
        migrations.AlterField(
            model_name='gearcomponentprofile',
            name='add_components',
            field=models.ManyToManyField(related_name='profile_add_components', to='mycyclediary_dot_com.Component'),
        ),
        migrations.AlterField(
            model_name='gearcomponentprofile',
            name='gear',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mycyclediary_dot_com.Gear'),
        ),
        migrations.AlterField(
            model_name='gearcomponentprofile',
            name='remove_components',
            field=models.ManyToManyField(related_name='profile_remove_components', to='mycyclediary_dot_com.Component'),
        ),
        migrations.AlterField(
            model_name='shoe',
            name='gear_ptr',
            field=models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='mycyclediary_dot_com.Gear'),
        ),
    ]
