language: python
python:
  - "2.7"
  - "3.2"
  - "3.3"
virtualenv:
  system_site_packages: true
env:
  - CYCLEDIARYCACHE_1_PORT_11211_TCP_PORT
  - CYCLEDIARYCACHE_1_PORT_11211_TCP_ADDR
  - CYCLEDIARYQUEUE_1_PORT_5672_TCP_PORT
  - CYCLEDIARYQUEUE_1_PORT_5672_TCP_ADDR
install:
  - "pip install -r requirements/test.txt --use-mirrors"
  - "pip install https://github.com/rgeyer/python-fitparse/tarball/master"
  - "cp ./mycyclediary_dot_com/settings/secrets.py.example ./mycyclediary_dot_com/settings/secrets.py"
script: "./manage.py test api"
