sudo: false
language: python
python:
  - 2.7
  - 3.6
env:
  - CYCLEDIARYCACHE_1_PORT_11211_TCP_PORT=1 CYCLEDIARYCACHE_1_PORT_11211_TCP_ADDR=0.0.0.0 CYCLEDIARYQUEUE_1_PORT_5672_TCP_PORT=1 CYCLEDIARYQUEUE_1_PORT_5672_TCP_ADDR=0.0.0.0
install:
  - "pip install -r requirements/test.txt"
  - "cp ./mycyclediary_dot_com/settings/secrets.py.example ./mycyclediary_dot_com/settings/secrets.py"
script:
  - coverage run $(which pytest)
after_success:
  - coveralls
after_script:
  - pylint mycyclediary_dot_com
