cyclediarycache:
  image: memcached
cyclediaryweb:
  build: .
  command: python manage.py runserver 0.0.0.0:80
  environment:
    - VIRTUAL_HOST=dev.mycyclediary.com
  volumes:
    - .:/code
  expose:
    - 80
  links:
    - cyclediarycache
